apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: file-collector
  namespace: harman-system
spec:
  template:
    spec:
      containers:
      - name: collector
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "opentelemetry-collector.monitoring.svc.cluster.local:4317"

