apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: harman-system
type: Opaque
stringData:
  # MySQL 연결 정보
  DB_HOST: "mysql.harman-system.svc.cluster.local"
  DB_PORT: "3306"
  DB_USER: "harman"
  DB_PASSWORD: "harman123!@#"
  DB_NAME: "harman"

